import React, { Component } from 'react';
import { Text } from 'react-native';
import { Platform, AsyncStorage, AppState, TouchableOpacity } from 'react-native';

import PushService from './scr/helpers/Api/PushService';
import Navigator from './scr/Components/Navigator';

import { NotificationsAndroid } from 'react-native-notifications';

export default class App extends Component {
  constructor() {
    super();

    PushService.addListeners();
  }

  componentDidMount() {

    /*NotificationsAndroid.localNotification({
      title: "Local notification",
      body: "This notification was generated by the app!",
      extra: "data"
    });*/
  }

  render() {
    return (
      <Navigator />
    );
  }
}