import React from 'react';
import { Text, View, TextInput, AppState, Platform } from 'react-native';
import Button from '../Button';
import Screen from './Screen';
import styles from '../../config';
import PushController from '../PushController';

import { NotificationsAndroid } from 'react-native-notifications';

//Helpers
import User from '../../helpers/Api/User';

class Register extends Screen {
    constructor(props) {
        super(props);

        this.state = {
            login: 'p[l',
            pass: 'lkjkl',
            confirm: '',
            responseText: '',
            seconds: 5
        }
        this.onRegHandler = this.onRegHandler.bind(this);
    }

    componentDidMount() {
        AppState.addEventListener('change', this.onRegHandler);
    }

    componentWillUnmount() {
        AppState.removeEventListener('change', this.onRegHandler);
    }

    onRegHandler = () => {
        var { login, pass } = this.state;

        User.register({
            email: login,
            password: pass,
            usertype: 'user'
        }, (response) => {
            this.setState({
                responseText: 'New user has been successfully registered!'
            });
        }, (error) => {
            this.setState({
                responseText: error
            });
        });

        NotificationsAndroid.localNotification({
            title: "Local notification",
            body: "This notification was generated by the app!",
            extra: "data"
        });
    }

    render() {
        return (
            <View style={styles.container}>
                <Text>{this.state.responseText}</Text>

                <TextInput
                    style={styles.textInput}
                    onChangeText={(val) => this.setState({ login: val })}
                />
                <TextInput
                    style={styles.textInput}
                    onChangeText={(val) => this.setState({ pass: val })}
                    textContentType={'password'}
                />
                <TextInput
                    style={styles.textInput}
                    onChangeText={(val) => this.setState({ confirm: val })}
                    textContentType={'password'}
                />

                <Button onPress={this.onRegHandler}
                    title='Register' />
            </View>
        );
    }
}

export default Register;